### ISSUE TITLE
[question] Create subvolume with subfolder /.snapshots that contains the leaves (subvolumes)

### ISSUE THREAD

**Issue by zilexa** [3coma3/btrfs-backup#19]
Currently, the script will create a subvolume "destination" and just put all snapshots in there (timeline folders). 
To match with other btrfs backup tools, it would be helpful if it would create a subvolume "destination" and create the leaf structure in a folder called `.snapshots`. 

Is this possible? Could you point me in the direction where to make changes in the script to do this?

I thought about:
- replacing `$destination/` with `$destination/.snapshots/` throughout the script (CTRL+H). 
- On line 90, replace `base="$destination"` with `base="$destination/.snapshots"
-

**Comment by zilexa** [comment]
I solved this now by creating the folders myself manually, and changed `destination` in my .conf file to /.../.../.snapshots.

**Comment by 3coma3** [comment]
I'm not sure if this is related to the feature you mention at the end in #17, but in case it's not. Why don't you just set destination to the path ending in .snapshots ?

**Comment by 3coma3** [comment]
I'm going to close this one, feel free to reopen as needed.
