### ISSUE TITLE
Add option for `--exclude`

### ISSUE THREAD

**Issue by tstenner** [3coma3/btrfs-backup#4]
On my backup source there are temporary files that shouldn't be saved.
With my current rsync backup, I have a list of `--exclude`s, e.g. `--exclude='*.DS_Store' --exclude="Thumbs.db" --exclude="@Recycle"` and so on.

It'd be great if there was a config option to exclude files.

**Comment by 3coma3** [comment]
Hi @tstenner,
It's a good idea, I'll try adding it over this weekend.

**Comment by 3coma3** [comment]
Here's a take on this. I've tested it with exclusion and inclusion rules and seems to work here.

See also the [comment](https://github.com/3coma3/btrfs-backup/commit/1c63b72ae3e123d59b520e7366945744e2263b95#commitcomment-34132910) in the commit

**Comment by tstenner** [comment]
Wow, this is much better than I had imagined it!

**Comment by 3coma3** [comment]
Glad you like it! :) Let's see if testing reveals some issue. One thing it occurred to me is the chance to define filters that apply to any source. I'll probably add that later on if it comes to be useful.

Should we close this issue or you prefer to leave it open a while until more tested?

**Comment by tstenner** [comment]
I'd close it, since the original issue (no --exclude) is resolved and until a bug is found I'll assume there are none. :-)
